### ISSUE TITLE
TestCafe doesn't see any tests - ERROR No tests to run

### ISSUE THREAD

**Issue by Grosha** [lilbaek/webstorm-testcafe#11]
I have a problem with running tests in Webstorm. I installed plugin 'TestCafe runner for WebStrom' and in Configuration select TestCafe. So when I try to run the test, the browser starts but TestCafe doesn't see any tests. I see error message:
`ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.`

I tried to run with:

1. set working directory - doesn't help
2. set node_modules folder (node_modules/testcafe/bin/testcafe.js) - have the error 
`internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'C:\Users\user\......\node_modules\testcafe\bin\testcafe.js\testcafe\lib\cli\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`
3. Did npm install rimraf -g && rimraf node_modules - doesn't help

Could you help me with set up configuration, because of it hard to get used Visual Studio after a very long period working with JetBrain products? 

PS: tests run from terminal and in Visual Studio

**Comment by lilbaek** [comment]
Hi Grosha,

When running tests you need to invoke it using a right-click.
![image](https://user-images.githubusercontent.com/3147748/77831542-11400a80-7130-11ea-83b7-cbdc4342a963.png)
This can be done on a specific test, a test fixture or on an entire folder:
![image](https://user-images.githubusercontent.com/3147748/77831551-21f08080-7130-11ea-863d-5eb7dd0a91b9.png)

Invoking it from the configuration/run button is not supported as it does not give any context to what tests you want to run,
