### ISSUE TITLE
"TestCafe runner for WebStorm" is incompatible after updating to build 201.SNAPSHOT < IU-202.6397.94)

### ISSUE THREAD

**Issue by sammie9xnt** [lilbaek/webstorm-testcafe#13]
"TestCafe runner for WebStorm" is incompatible after updating to build 201.SNAPSHOT < IU-202.6397.94)

**Comment by lilbaek** [comment]
I have released a new update today that enables 2020.02 support. It normally takes 1/2 days for Jetbrains to approve it.
