### ISSUE TITLE
Test run fails if test is in a nested directory

### ISSUE THREAD

**Issue by ykh-hamed** [lilbaek/webstorm-testcafe#3]
if you have a package structure like:
```
/
mytests
  -- test.js
package.json
```
the test fails because can't find the testcafe module. I believe it's due to the hardcoded `node_modules/testcafe/lib/cli/index.js`

**Comment by lilbaek** [comment]
I have added support for setting a specific node_modules folder to use.
![image](https://user-images.githubusercontent.com/3147748/69604833-d5305800-101e-11ea-9885-9534fe00904b.png)
