### ISSUE TITLE
Overall test status displayed incorrectly

### ISSUE THREAD

**Issue by camueller** [lilbaek/webstorm-testcafe#6]
Although the test run finishes with "Process finished with exit code 0" the status is displayed as "test framework quit unexpectedly":

![Screenshot_20191231_142317](https://user-images.githubusercontent.com/4489628/71622888-1943e900-2bd9-11ea-8229-b77bb77720f5.png)

**Comment by lilbaek** [comment]
What version of the plugin are you running? Some of the early versions had this issue but the latest version should do this correctly.
![image](https://user-images.githubusercontent.com/3147748/71716001-9ce91a00-2e13-11ea-986e-8a40c4606da1.png)

**Comment by camueller** [comment]
I'm using version 1.3.1.

**Comment by lilbaek** [comment]
What is your testcafe version?
Also, could you paste the command line arguments that is used to run testcafe?
Something like: "data/opt/node/bin ...."

If possible I would like a repo that I can try and replicate it with.

**Comment by camueller** [comment]
I'm using the latest version of Testcafe - 1.7.1.
Perhaps this issue is related to the fact that I'm using more than one content root in WebStorm:

![image](https://user-images.githubusercontent.com/4489628/71717776-729a5b00-2e19-11ea-8ecd-a1beb96466f3.png)

You can use my repo - it is open source: https://github.com/camueller/SmartApplianceEnabler
For testing I would recommend testcafe.spec.ts.

**Comment by lilbaek** [comment]
I am not able to replicate the issue with your repository. 
I have tested on both Ubuntu 19 and Windows with your repository and it works as expected.
![image](https://user-images.githubusercontent.com/3147748/71820123-81d60e80-308e-11ea-8fc4-0a330d5e8989.png)
Have you tried specifying a specific node_modules folder to use?
Like:
![image](https://user-images.githubusercontent.com/3147748/71820258-e85b2c80-308e-11ea-9f52-90f4c9f52aa3.png)
